from pygame.math import Vector2 as vec

APP_WIDTH = 560
APP_HEIGHT = 720
TOP_BUFFER = 50
BOTTOM_BUFFER = 50
MAP_WIDTH = APP_WIDTH  # 588
MAP_HEIGHT = APP_HEIGHT - TOP_BUFFER - BOTTOM_BUFFER  # 684
CELL_WIDTH = MAP_WIDTH // 28
CELL_HEIGHT = MAP_HEIGHT // 30

PLAYER_WIDTH = 32
PLAYER_HEIGHT = 45
PLAYER_X_INDENT = 6
PLAYER_Y_INDENT = 16


PLAYER_SPRITE_HEIGHT = 56
PLAYER_SPRITE_WIDTH = 40

PLAYER_START_POS = vec(13, 23)
