from pygame.math import Vector2 as vec

APP_WIDTH = 560
APP_HEIGHT = 720
TOP_BUFFER = 50
BOTTOM_BUFFER = 50
MAP_WIDTH = APP_WIDTH  # 588
MAP_HEIGHT = APP_HEIGHT - TOP_BUFFER - BOTTOM_BUFFER  # 684
CELL_WIDTH = MAP_WIDTH // 28
CELL_HEIGHT = MAP_HEIGHT // 30

PLAYER_WIDTH = 20
PLAYER_HEIGHT = 30
PLAYER_X_INDENT = (PLAYER_WIDTH-CELL_WIDTH)//2
PLAYER_Y_INDENT = (PLAYER_HEIGHT-CELL_HEIGHT)//2


PLAYER_SPRITE_HEIGHT = 56
PLAYER_SPRITE_WIDTH = 40

########## HORIZONTAL
NUMBER_OF_ENEMIES = 3
ENEMY_WIDTH = 41
ENEMY_HEIGHT = 30
ENEMY_SPRITE_HEIGHT = 120
ENEMY_SPRITE_WIDTH = 164
ENEMY_X_INDENT = (ENEMY_WIDTH-CELL_WIDTH)//2
ENEMY_Y_INDENT = (ENEMY_HEIGHT-CELL_HEIGHT)//2

########## VERTICAL
'''ENEMY_WIDTH = 30
ENEMY_HEIGHT = 41
ENEMY_SPRITE_HEIGHT = 164
ENEMY_SPRITE_WIDTH = 120
ENEMY_X_INDENT = ENEMY_WIDTH-CELL_WIDTH
ENEMY_Y_INDENT = ENEMY_HEIGHT-CELL_HEIGHT'''


PLAYER_START_POS = vec(13, 23)
ENEMY_START_POS = [vec(13, 11), vec(12, 14), vec(15, 14)] #vec(13, 14), vec(15, 14)]
