APP_WIDTH = 560
APP_HEIGHT = 720
TOP_BUFFER = 50
BOTTOM_BUFFER = 50
MAP_WIDTH = APP_WIDTH  # 588
MAP_HEIGHT = APP_HEIGHT - TOP_BUFFER - BOTTOM_BUFFER  # 684
CELL_WIDTH = MAP_WIDTH // 28
CELL_HEIGHT = MAP_HEIGHT // 30

